<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class HeaderGrabOptions {
	private $header_grab_options_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'header_grab_options_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'header_grab_options_page_init' ) );
	}

	public function header_grab_options_add_plugin_page() {
		add_management_page(
			'Header Grabber', // page_title
			'Header Grabber', // menu_title
			'manage_options', // capability
			'header-grab-options', // menu_slug
			array( $this, 'header_grab_options_create_admin_page' ) // function
		);
	}

	public function header_grab_options_create_admin_page() {
		$this->grab_header();
		$this->header_grab_options_options = get_option( 'header_grab_options_option_name' ); ?>

		<div class="wrap">
			<h2>Header Grabber Settings</h2>
			<p style="margin-right:30%">The textarea here will be filled with the code curled from the URL. That code will be used in the header. A cron job has been added to curl the URL twice daily. It will also be curled when this options page is loaded – great for manually loading when testing!</p>
			<p style="margin-right:30%">If for any reason the curl fails, the header code will not be updated.</p>
			<p style="margin-right:30%">[header_grabber] shortcode can also be used to display the code.</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'header_grab_options_option_group' );
					do_settings_sections( 'header-grab-options-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function grab_header(){
		//Get entire option array
		$all_options = get_option( 'header_grab_options_option_name' );
		$header_url = $all_options['url_to_grab_0'];
		$header_code = (@file_get_contents($header_url));

		if ( null != $header_code) {
			$all_options['header_code_1'] = $header_code;
			//Update entire array
			update_option('header_grab_options_option_name', $all_options);
		}else{
			add_settings_error('header_grab_options_option_group', '2781', 'WARNING: The set URL did not return anything. The current header code will remain unchanged.', 'error');
		}
	}

	public function header_grab_options_page_init() {
		register_setting(
			'header_grab_options_option_group', // option_group
			'header_grab_options_option_name', // option_name
			array( $this, 'header_grab_options_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'header_grab_options_setting_section', // id
			'', // title
			array( $this, 'header_grab_options_section_info' ), // callback
			'header-grab-options-admin' // page
		);

		add_settings_field(
			'url_to_grab_0', // id
			'URL To Grab', // title
			array( $this, 'url_to_grab_0_callback' ), // callback
			'header-grab-options-admin', // page
			'header_grab_options_setting_section' // section
		);

		add_settings_field(
			'header_code_1', // id
			'Header Code', // title
			array( $this, 'header_code_1_callback' ), // callback
			'header-grab-options-admin', // page
			'header_grab_options_setting_section' // section
		);

	}

	public function header_grab_options_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['url_to_grab_0'] ) ) {
			$sanitary_values['url_to_grab_0'] = sanitize_text_field( $input['url_to_grab_0'] );
		}

		if ( isset( $input['header_code_1'] ) ) {
			$sanitary_values['header_code_1'] = $input['header_code_1'];
		}

		return $sanitary_values;
	}

	public function header_grab_options_section_info() {
		
	}

	public function url_to_grab_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="header_grab_options_option_name[url_to_grab_0]" id="url_to_grab_0" value="%s">',
			isset( $this->header_grab_options_options['url_to_grab_0'] ) ? esc_attr( $this->header_grab_options_options['url_to_grab_0']) : ''
		);
	}

	public function header_code_1_callback() {
		printf(
			'<textarea readonly class="large-text" rows="10" name="header_grab_options_option_name[header_code_1]" id="header_code_1">%s</textarea>',
			isset( $this->header_grab_options_options['header_code_1'] ) ? esc_attr( $this->header_grab_options_options['header_code_1']) : ''
		);
	}

}
if ( is_admin() )
	$header_grab_options = new HeaderGrabOptions();

/* 
 * Retrieve this value with:
 * $header_grab_options_options = get_option( 'header_grab_options_option_name' ); // Array of All Options
 * $url_to_grab_0 = $header_grab_options_options['url_to_grab_0']; // URL To Grab
 * $header_code_1 = $header_grab_options_options['header_code_1']; // Header Code
 */
